Fix Sketch Palettes for Sketch 53
andrewfiorillo/sketch-palettes pull request #78
Opened 2019-02-07 14:26 UTC by kristof

I'm able to load, save and clear palettes again **ONLY** for document colors.
Sketch appears to have removed `app.globalColors`, still figuring out the proper replacement for this.

But at least some if it is working again.

2019-02-07 16:19 UTC, kristof commented
And global colors + gradients is also fixed.

2019-02-07 16:25 UTC, mathieudutour requested changes

2019-02-07 16:25 UTC, mathieudutour commented on Sketch Palettes.sketchplugin/Contents/Sketch/sketchPalettes.js
> +		MSPersistentAssetCollection.sharedGlobalAssets();
```suggestion
		var assets = MSPersistentAssetCollection.sharedGlobalAssets();
```

2019-02-07 16:25 UTC, mathieudutour commented on Sketch Palettes.sketchplugin/Contents/Sketch/sketchPalettes.js
> +				colorAssets.push(MSColorAsset.alloc().initWithAsset_name(mscolor, ''));
```suggestion
				colorAssets.push(MSColorAsset.alloc().initWithAsset_name(mscolor, null));
```

2019-02-07 16:25 UTC, mathieudutour commented on Sketch Palettes.sketchplugin/Contents/Sketch/sketchPalettes.js
> +				gradientAssets.push(MSGradientAsset.alloc().initWithAsset_name(msgradient, ''));
```suggestion
				gradientAssets.push(MSGradientAsset.alloc().initWithAsset_name(msgradient, null));
```

2019-02-07 16:25 UTC, kristof commented
@andrewfiorillo Let me if any edits are needed + how you want to bump the version number.

2019-02-07 16:31 UTC, kristof commented
@mathieudutour thanks for the suggestions and a moment of your valuable time!

2019-02-07 23:38 UTC, merged

2019-02-07 23:50 UTC, andrewfiorillo commented
@kristof  @mathieudutour thanks for all of your help getting this fixed up! Really appreciate it.

2019-02-08 14:35 UTC, himynameisubik commented
Amazing guys @kristof @mathieudutour @andrewfiorillo , thanks a lot for fixing this so fast!